### ISSUE TITLE
Name Standard

### ISSUE THREAD

**Issue by Sveino** [digin-energi/Grunnprofil#11]
Document the name standard used in the DIGIN10 test model.
Everyone that is contributing with model to DIGIN would need to follow this standard. DIGIN might make this a general recommendation for model that is going to be exchanged between utility in Norway.
DIGIN will recommend software vendors that are delivering or planning to deliver application software that support CIM to follow this standard either as out of the box or as possibility to be configured. 
This naming standard if focusing on CIM objects, not all of them are directly connected to physical elements, e.g. cim:Terminal, cim:ConnectivityNode. 
The first version should focus on the following:

- cim:ACLineSegment
- cim:BasePower
- cim:BaseVoltage
- cim:Bay
- cim:Breaker
- cim:BusbarSection
- cim:ConformLoad
- cim:ConformLoadGroup
- cim:ConnectivityNode
- cim:ControlArea
- cim:CurrentLimit
- cim:Disconnector
- cim:EquivalentInjection
- cim:Feeder
- cim:Fuse
- cim:GeographicalRegion
- cim:Line
- cim:LinearShuntCompensator
- cim:LoadArea
- cim:LoadBreakSwitch
- cim:OperationalLimitSet
- cim:OperationalLimitType
- cim:PetersenCoil
- cim:PowerTransformer
- cim:PowerTransformerEnd
- cim:RatioTapChanger
- cim:RegulatingControl
- cim:SubGeographicalRegion
- cim:SubLoadArea
- cim:Substation
- cim:TapChangerControl
- cim:Terminal
- cim:VoltageLevel
-

**Comment by hemaglu** [comment]
The namestandard was included in first release
