### ISSUE TITLE
Include Fuse in DIGIN10 model

### ISSUE THREAD

**Issue by EmilieSkog** [digin-energi/Grunnprofil#204]
- [x] Change from Breaker to Fuse after CIM17 conversion.
- Should change mRID of all breakers that are converted to fuses. (and associated terminals)
- [x] Update documentation for Fuse

**Comment by Sveino** [comment]
Fuse and associated Terminal needs to get new mRID.

**Comment by EmilieSkog** [comment]
We consider the upgrade from CGMES v3.0 an update from CGMES v2.4 and will therefore not change the mRIDs of the Breaker/Fuses and related Terminals
