### ISSUE TITLE
Modify folder and file structure

### ISSUE THREAD

**Issue by Sveino** [digin-energi/Grunnprofil#219]
DIGIN10 v1.0 and DIGIN10 v2.0 has primary looked at the initial Grid Model, without taking market, asset or schedule information into account. We would like to have a structure that can capture that. This is related to filename standard (link:)
New structure:
DIGIN10 
   [v1.0] (move to separate 'Read-only' branch)
   [v2.0] (move to separate 'Read-only' branch)
   [v2.x] (all item are moved up)
       [Asset]
          manifest.xml
          manifest.jsonld
          [CIMXML]
              (Asset, AssetCatalog, Customer, MeterReading Reference Model)
          [jsonld]
       [Grid]
          manifest.xml
          manifest.jsonld
          [CIMXML]
              {all the file we currently have on the top level)
          [jsonld]
       [Market]
       [Schedule]
          [2022] (Year)
             [01] (month)
                [12] (day)

**Comment by StigLotuft** [comment]
#223 Resolves this issue.

**Comment by Sveino** [comment]
This was created with existing files any new files may need to create relevant folders.
