### ISSUE TITLE
Filename standard

### ISSUE THREAD

**Issue by Sveino** [digin-energi/Grunnprofil#220]
In CIM we generally do not want to have any naming standard, so this should not be used by application. However, a good naming standard is very useful for the human.
The initial model file does not follow the naming standard since it provides the baseline. The naming standard is particularly relevant when we deal with schedule data (data valid for a given time)

Suggest to base DIGIN naming standard on ENTSO-E QoCDC v3.3:

The following mask is to be used to have a valid file name: 
<effectiveDateTime>_<businessProcess>_<sourcingActor>_<modelPart>_<fileVersion>
The following additional rules applies for IGM and CGM file names with this mask
• The parts in the file name are not allowed to contain an underscores “_” or dashes “-The dashes are reserved for sub parts within the sourcingActor. 
• All four underscores shall be present
If a file name part is not used it shall be left empty resulting in two consecutive underscores “__”.
• For <modelPart> SSH, TP and SV all five parts in the mask shall be present.
• For <modelPart> EQ and EQDIFF the <businessProcess> may be absent meaning that the CIMXMLfile can be used with any business process. The mask to use is then
• <effectiveDateTime>__<sourcingActor>_<modelPart>_<fileVersion>
The sourcingActor field has three different layouts
1. <sourcingTSO> is used to identify the source of IGMs
2. <sourcingRSC>-<synchronousArea> is used for SV files relating to the synchronousArea  from an RSC 
3. <sourcingRSC>-<synchronousArea>-<sourcingTSO> is used for SSH files relating to a CGM from an RSC where the sourcingTSO relates to the IGM that has been used to create the CGM. 
The allowed <synchronousArea> names are listed in level 1 rule SynchronousArea.
Examples:
• 20180118T0930Z_1D_APG_SSH_1.xml
• 20180118T0930Z_1D_APG_SSH_001.xml 
• 20180117T2230Z_1D_APG_EQ_1.xml 
• 20180117T2230Z_1D_APG_EQ_001.xml 
• 20180117T2230Z__APG_EQ_001.xml 
• 20180118T1130Z_1D_TSCNET-CEU_SV_001.xml 
• 20180118T1130Z_1D_TSCNET-CEU-APG_SSH_001.xml

**Comment by ThomasRanvikEriksen** [comment]
Example for IntervalReading json Timeseries:
Schedule\2022\10\12\20221012T230000Z_D1_LV1_IR_1.json

**Comment by Sveino** [comment]
#238
