### ISSUE TITLE
Add PowerTransformer as Asset and AssetInfo related to the oil measurement

### ISSUE THREAD

**Issue by Sveino** [digin-energi/Grunnprofil#248]
Add one Power Tranformer Asset and AssetInfo
![image](https://user-images.githubusercontent.com/15873106/200844652-1c23cdb6-a643-4f76-9165-e1f73a76d412.png)

We will include TapChangesInfo, but not in this version.
![image](https://user-images.githubusercontent.com/15873106/200845253-197b2197-ee84-46de-bd72-5f58a94c0994.png)
Asset link to PowerTransformerInfo.
Adding NEK and DIGIN extension will be address in later issues.

**Comment by EmilieSkog** [comment]
Reference to DIGIN Produktdata extenstions to relevant transformer infos:
https://github.com/digin-energi/produktdata-public#uml-class-diagram-1
